### ISSUE TITLE
[Bug]: Shift-command-left/right in "rename in place" exits

### ISSUE THREAD

**Issue by M0rtenB** [mikekazakov/nimble-commander#282] opened 2024-05-14 16:45 UTC
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

Version 1.5.0 (3981), Sonoma 14.5

### Distribution Type

Downloaded directly from the website

### Expected Result

While in the "Rename in Place" functionality, I expect shift-cmd-left and shift-cmd-right to select the part of the text between the cursor and the beginning/end of the filename. This is muscle memory and part of my workflow for quickly substituting another extension or similar.

### Actual Result

The rename is instantly exited, and any changes implemented, same as if I had pressed enter.

### Steps to reproduce

1. Choose file. 2. Rename in place. 3. Press shift-cmd-right. 4. Observe.

**Comment by M0rtenB** [comment] 2024-05-14 16:49
Just realized that this is because these shortcuts are set to "Focus left panel" and "Focus right panel" as standard. Well, that's perhaps somewhat confusing for a Mac user.

**Comment by mikekazakov** [comment] 2024-05-14 17:27
Duplicate of #214.

**Closed by mikekazakov** 2024-05-14 17:27 UTC
Labels: bug
