### ISSUE TITLE
Changing directories while copy in progress is not working correctly

### ISSUE THREAD

**Issue by nitrostudios** [mikekazakov/nimble-commander#164] opened 2024-03-22 06:13 UTC
Changing directories while copy in progress is not working correctly, it's even more pronounced when using SMB shares. When trying to change the directory, it will briefly switch and then get back to the former directory or some other random directory. So it's basically unusable while operation is in progress.

NC Version 1.6.0 (4042)

**Comment by mikekazakov** [comment] 2024-03-23 17:37
Can't reproduce - more input is needed.

**Comment by nitrostudios** [comment] 2024-03-25 09:22
When the copy operation is in progress from or to NAS, sometimes it won't even change the directory until the operation is over or it takes very long time or it briefly changes the directory and then get back to the former one... I don't know what is going on, unfortunately, do not have enough time to test it :( But there are a lot of small thing like this, e.g. directory listing is very slow. For me very good benchmark is Total Commander, it works a lot faster when listing files, for example and does not have such issues when changing directory.

**Comment by mikekazakov** [comment] 2024-03-25 10:40
Is it the same SMB server? https://github.com/mikekazakov/nimble-commander/issues/99

**Comment by nitrostudios** [comment] 2024-03-25 10:46
Yes, same server, Synology DSM 7.2.1-69057 Update 3.

**Comment by mikekazakov** [comment] 2024-03-25 10:52
Well I thought we already established that issues with this server manifest themselves on MacOS outside NC as well, so I'm not sure if NC can do anything here at all.

**Comment by nitrostudios** [comment] 2024-03-25 10:59
Directory listing speed and changing while copy in progress is happening also on my Windows Server 2021. I would like to test some more, but right now not enough time :( But want to try different Windows Server versions, 2019, 2021 and 2023 to see the difference. Just funny fact, none of that is happening on Windows 10, I have a feeling that the samba implementation in the macOS is really bad.

**Comment by mikekazakov** [comment] 2024-03-25 11:11
I'm sorry, but the issue has nothing to do with NC and for sure I can't reproduce it locally, so closing now.

**Closed by mikekazakov** 2024-03-25 11:11 UTC
Labels: question

**Comment by nitrostudios** [comment] 2024-03-25 12:24
I've just updated to NC Version 1.6.0 (4049) and I can browse folders not problem even when operation is in progress :)

**Comment by silicooon** [comment] 2024-03-25 13:32
There are many times I wished NC was “fast” enough like TotalCommander.
But I feel like the main issue here is that the app its based on MacOS in general. 
I am using unraid system and sometimes copies are really fast and others not.  
(I guess its not using the same disk all the time, there are 11 of them in there, so no proper way to check it unfortunately)

The only thing I can say is that NC is slow on showing a directory with files/folders close to 1000 and if more then the time is double.. Server is SMB, and I am using the right Smb options for v3+ on mac.

**Comment by mikekazakov** [comment] 2024-03-25 14:41
Please don't mix up Nimble Commander and the SMB driver maintained by Apple (https://github.com/apple-oss-distributions/SMBClient). NC doesn't distinguish SMB connections and other filesystems mounted in the same UNIX file tree - it uses the same APIs for all these cases and if there's a problem in the SMB driver it should be reported to Apple.  
On the other hand, if there's a clear case when other software on MacOS performs measurably and reproducibly better than NC (given comparable functionality of course) - that's worth a detailed bug report on NC.
