### ISSUE TITLE
[Bug]: The built-it Terminal does not respond to keyboard and does not do anything

### ISSUE THREAD

**Issue by vladstudio** [mikekazakov/nimble-commander#306] opened 2024-06-17 07:36 UTC
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

Version 1.6.0 (4087), OS 14.5 (23F79)

### Distribution Type

Downloaded directly from the website (including Brew)

### Expected Result

---

### Actual Result

The built-it Terminal does not respond to keyboard and does not do anything (the cursor blinks though).

### Steps to reproduce

Not sure how to reproduce this.

### Additional Information

https://github.com/mikekazakov/nimble-commander/assets/914320/b0792137-759e-4298-9f3d-f6b91c94d2df

**Comment by mikekazakov** [comment] 2024-06-17 17:08
Hm, haven't seen this issue in quite a while...
Some questions:
- what shell do you use? (Preferences->Terminal->Open shell with:...)
- does log show anything interesting? (Alt+Help->Debug->Show Logs->term->Trace)
- do you have anything special in your shell's startup config?

**Comment by vladstudio** [comment] 2024-06-17 19:25
* /opt/homebrew/bin/fish (switching to default shell does not help though)
* nope, logs window stays empty
* here's the screenshot
<img width="436" alt="image" src="https://github.com/mikekazakov/nimble-commander/assets/914320/a601263d-e74c-4ea2-9c83-4f1a988b29df">

**Comment by mikekazakov** [comment] 2024-06-17 19:29
Fish isn't a supported shell: 
<img width="842" alt="Screenshot 2024-06-17 at 20 26 50" src="https://github.com/mikekazakov/nimble-commander/assets/7439287/d0856d2f-b695-4cef-8352-2eb303399cac">

Could you try restarting NC after changing the setting to the default shell?

**Comment by vladstudio** [comment] 2024-06-17 19:31
I did! alas, did not help.

**Comment by mikekazakov** [comment] 2024-06-17 19:39
Hm, by any change your default login shell is also fish?
In any case, the logs should show what's going on under the hood, just make sure to set the appropriate logging level before making any actions.

**Comment by vladstudio** [comment] 2024-06-18 05:42
Hey, setting NC's shell explicitly to /bin/bash helped!

**Comment by vladstudio** [comment] 2024-06-18 05:43
If anyone is having the same problem:
- the problem was probably my default (OS-wide) shell is set to `/opt/homebrew/bin/fish`. 
- in NC settings, I set "open shell with" to `/bin/bash` and got internal terminal working.

**Comment by mikekazakov** [comment] 2024-06-18 08:05
Ok, closing as not a bug.

**Closed by mikekazakov** 2024-06-18 08:05 UTC
Labels: bug
