### ISSUE TITLE
[Bug]: Can't delete files or folders inside OneDrive folder

### ISSUE THREAD

**Issue by zouyangdev** [mikekazakov/nimble-commander#299] opened 2024-06-13 03:23 UTC
### Confirmation

- [X] I have read the contributing guidelines

### Version of Nimble Commander

v1.6.0 MacOS 13.6.5

### Distribution Type

Downloaded from Mac App Store (i.e. sandboxed)

### Expected Result

Delete a file or folder inside OneDrive folder, really delete it.

### Actual Result

After deleting ~/OneDrive/some/folder/myfile.txt, the file is moved to ~/OneDrive/myfile.txt.

### Steps to reproduce

Steps: 

1. Focus a file or folder inside OneDrive folder, e.g. ~/OneDrive/some/folder/myfile.txt
2. Delete it with ⌘Backspace or F8, the file will be automatically moved to ~/OneDrive/myfile.txt
3. Delete the file ~/OneDrive/myfile.txt again, it will be moved to ~/OneDrive/myfile 2.txt
4. Delete again, it will be moved to ~/OneDrive/myfile 3.txt
5. etc

<img width="551" alt="Snipaste_2024-06-13_11-21-05" src="https://github.com/mikekazakov/nimble-commander/assets/1446549/c44696b4-d11f-4108-bf97-eef7b11c8010">

<img width="496" alt="Snipaste_2024-06-13_10-27-41" src="https://github.com/mikekazakov/nimble-commander/assets/1446549/13325ff6-68fb-42e3-aa92-cb8764b4a426">

**Comment by mikekazakov** [comment] 2024-06-13 08:49
Hi, a couple of questions:
- does the same behaviour occurs with a non-sandboxed version?
- what happens if you do the same via "rm" from a terminal?

**Comment by zouyang08** [comment] 2024-06-13 10:39
What is non-sandboxed version? Is it the version from the website? I'll have a try.
Using iTerm, there is no problem with the deletion. The file is really deleted.
Using Finder, there is no problem too, the file is deleted to the Trash.
Btw, the App Store version, when I use ⇧F8, the file can be deleted. But it is permanently deleted, none in the Trash.

**Comment by zouyang08** [comment] 2024-06-13 10:47
I have tested the website version, the same issue still exists.

**Comment by mikekazakov** [comment] 2024-06-13 12:02
So then the issue is about moving to trash, not about deletion, right?

**Comment by mikekazakov** [comment] 2024-06-14 09:15
Another question - is the Full Disk Access enabled in your case and if not - does it affect the issue?

**Comment by zouyang08** [comment] 2024-06-14 11:39
The app store version, Full Disk Access is not enabled, Folder access of OneDrive is granted.
I removed the app store version, and installed website version, this time Full Disk Access in enabled. The issue is still the same.

**Comment by zouyang08** [comment] 2024-06-14 11:52
UPDATE: I tested in another Mac machine, MacOS Sonoma 14.5, Nimble Commander from App Store, Folder access of OneDrive granted. This time deletion inside OneDrive is OK, except a little difference to Finder. The file is permanently deleted using F8 or Cmd-Backspace. As in Finder, the deletion is to Trash with Cmd-Backspace.
In both machine, OneDrive is the latest version.
If searching for OneDrive issues takes too much time, just leave it.

**Closed** 2024-11-27 05:58 UTC
Labels: bug, question
